SwiftSoup.xcodeproj/project.pbxproj

The Product Name field for the tvOS, watchOS, and macOS framework targets was misspelled `SwitSoup`, which causes an issue when linking to the compiled framework(e.g. by using Carthage) on those platforms as described in #52.

Fix Product Name tvOS, watchOS, macOS frameworks

---

Sources/Entities.swift
Tests/SwiftSoupTests/EntitiesTest.swift

[WIP] Remove StringBuilder

---

Sources/Attribute.swift
Sources/Entities.swift
Sources/TextNode.swift
Tests/SwiftSoupTests/EntitiesTest.swift

This is a follow on PR to #70 that actually stops the `Entities.escape` method from using `StringBuilder`.

Remove all reference to StringBuilder in Entities.escape

---

README.md

The try statements in the README are already handled within do/catch blocks, so there's no need to disable error propagation and force a runtime error.
Thanks for the library!

Remove forced runtime errors in do/catch blocks in README

---

Sources/Pattern.swift
Sources/SwiftSoup.swift

1. The `Pattern` helper is useful, however, it's matcher method isn't `public`
2. When trying to reference types inside of the `SwiftSoup` module that have the same names as a type outside the module, the swift compiler emits an ambiguous reference error. For example `Pattern` has an ambiguous reference. And trying to say `SwiftSoup.Pattern`, the compiler says the SwiftSoup class doesn't have a member `Pattern`. Removing the class `SwiftSoup` helps the compiler know that `SwiftSoup` refers to the module and only the module, and not the class.

Two Accessibility Changes

---

Sources/Node.swift

SwiftSoup does not build on swift linux 4.2 in "release" mode, see https://travis-ci.org/scinfu/SwiftSoup/jobs/438795328. SIL doesn't like the code (though it looks fine). 
This PR removes what appears to be an optimization when compiling for linux, which appears to resolve the issue for linux.
MacOS is not affected by this issue or this PR.
This PR resolves #101.

Fixes #101 - SwiftSoup builds in "release" mode on swift linux 4.2.

---

Sources/Elements.swift
Tests/SwiftSoupTests/ElementsTest.swift

I replaced the Sequence extension on Elements with RandomAccessCollection.
The makes the Elements class more like a Swift Array, and gets Sequence
support for free, removing the need for ElementsIterator.

Provide a RandomAccessCollection extension for Elements

---

Sources/StringBuilder.swift

In my tests with a large html file `document.html()` was taking 5 seconds. With the change to use `join` rather than `reduce` that time was cut down to 0.072 seconds (almost 100x better).
I'm assuming that `join` is smarter about allocating the memory needed up front, where as `reduce` could spend a lot of time re-allocating and moving things in memory.

joined() seems to be much more efficient than reduce()

---

.travis.yml
Sources/HtmlTreeBuilderState.swift

I've fixed and updated travis-ci tests, they failed for some reason. Now they working on:
- linux, swift 4.2.4
- linux, swift 5.0.3
- linux, swift 5.1.5
- osx, xcode 10.1, swift 4.2.1
- osx, xcode 10.2, swift 5.0.1
- osx, xcode 11.3, swift 5.1.3
Yet there's no development sanpshots. e.g. swift 5.2. But i'll be glad to add it with another PR when they'll be released.
Also there were compilation warnings in `Sources/HtmlTreeBuilderState.swift` so i've fixed them too.

Fix travis tests

---

SwiftSoup.xcodeproj/project.pbxproj

Swift has been going through some changes in string implementation lately, so I checked performance on Xcode 12 beta and Swift 5.3. Everything seems to be stable; no updates needed.
However, I noticed that every target in the Xcode project has its optimization for the Release build set to "none". Is this intentional? I'm not 100% sure of this, but I believe that if you just use the package normally through Carthage or SPM, you get the regular Release build. And SwiftSoup benefits greatly from optimization.
This PR just deletes all the target-specific optimization settings and lets them inherit from the top-level project, where they are -Ospeed and -Onone for Release and Debug, respectively.

Remove explicit optimization settings for targets

---

Package.swift

Xcode 13.2 generates a warning now for packages which don't use Swift 5.0 or higher.

swift-tools 5.0

---

Sources/Attribute.swift

The `controls` attribute used by the `video` element is a boolean attribute.

add controls as boolean attribute

---

Sources/Mutex.swift

pthreads aren't available on Windows, so we reach for Windows syncing primitives instead.

Add Windows support

---

Sources/NodeTraversor.swift
Sources/NodeVisitor.swift
Tests/SwiftSoupTests/NodeTraversorTest.swift

Currently, `NodeTraversor` crashes when its `NodeVisitor` removes the current `Node` from `tail()`. This change safeguards that behavior by bookkeeping `.parent()` and `.nextSibling()` inside the traversal loop.
Also added a test class for `NodeTraversor` with a test for `head()` and `tail()` traversal order.

Support NodeVisitor.tail() removing Node

---

Sources/TokeniserState.swift

In Swift, there's [no implicit fallthrough](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/controlflow/#No-Implicit-Fallthrough) in `switch` cases. You have to make the [fallthrough](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/controlflow/#No-Implicit-Fallthrough) explicit by using `fallthrough` at the end of the case.
Tests are passing and this aligns with Jsoup.

Add explicit fallthrough in `Doctype` state

---

README.md

As @scinfu requested in #240, here is an updated version of README.md, which explains how to clean `<head>`.

Update README.md with new `Cleaner` init

---

Sources/Element.swift

this is valid in html for many years now and is ignored. this makes it easier to use the output in both html and xhtml pages, which otherwise fail for eg `<img>`.

selfclosing for html too

---

Sources/HtmlTreeBuilderState.swift
Tests/SwiftSoupTests/HtmlParserTest.swift

This fixes #253 - backported from jhy/jsoup#906

Allow rctext / rcdata tags to self-close.

---

.github/workflows/swift.yml

This workflow should build and test on the latest Swift 5 release as well as 5.7 on both MacOS and Linux when pull requests are created targeting master or there is a push to master.
This should keep future pull requests from breaking tests.
Note: This pull requests will show "some checks were not successful" since there are tests currently failing (see #260), but the action works as intended.

Setup github action to test build for pull requests/push for master

---

README.md

This PR addresses an issue that came up in our university software project team in the Netherlands regarding the political reference found within the readme.
First of all, thank you for developing and maintaining this library, we audited many HTML parsing libraries and we found this one the best, from usability, ease of installation and well-maintainedness perspectives. 
We have an Israeli team member in our team, and he was strongly opposed to using this library because of the BDS promotion. I myself usually stand very far from politics, but I wanted to dig a bit deeper to see why he was opposing so much, even though he is very much advocating against the war between Palestine and Israel. 
> I am not an expert in politics, and I want to restate that all my information on this topic is …

Remove political references from the repository

---

Package.swift
Sources/CharacterReader.swift
Sources/Entities.swift
Sources/Tokeniser.swift
Sources/TokeniserState.swift
Tests/SwiftSoupTests/AttributeParseTest.swift
Tests/SwiftSoupTests/CharacterReaderTest.swift
Tests/SwiftSoupTests/CleanerTest.swift
Tests/SwiftSoupTests/DocumentTest.swift
Tests/SwiftSoupTests/ElementTest.swift
Tests/SwiftSoupTests/HtmlParserTest.swift
Tests/SwiftSoupTests/XmlTreeBuilderTest.swift

I haven't benchmarked yet, but in theory this should be faster
Haven't fully tested yet either
Note that this increases the minimum platform versions

UTF-8 view optimizations + Regression fix for #275

---

Sources/String.swift

This alternative to displayName is more suitable to the charset attribute because it emits IANA-compatible MIME types or throws an error if the String encoding has no equivalent MIME type.
This is a purely additive change with no behavioral changes. Ideally the current uses of String.Encoding/displayName would be replaced with this new mimeName method in order to generate HTML attributes that are more correct.
Related to https://github.com/scinfu/SwiftSoup/issues/279

Add mimeName to String.Encoding.

---

Package.swift
SwiftSoup.podspec

After #276, package compilation now fails with
'UTF8View' is only available in watchOS 6.0 or newer
'utf8' is only available in watchOS 6.0 or newer
Bumps required version to watchOS 6, which came out at the same time that iOS 13 did.

require watchOS v6 or higher

---

.gitignore

This the folder where SwiftPM stores build artifacts when building from the command line (e.g. with `swift build`), hence we should ignore it to avoid accidentally committing it.

Add SwiftPM's `.build` to the gitignore

---

Package.swift

When building the project from the command-line using `swift build`, SwiftPM currently warns about not excluding a couple of plists:
```
$ swift build
warning: 'swiftsoup': found 4 file(s) which are unhandled; explicitly declare them as resources or exclude from the target
<path to swiftsoup>/Sources/InfoMac.plist
<path to swiftsoup>/Sources/InfotvOS.plist
<path to swiftsoup>/Sources/Info.plist
<path to swiftsoup>/Sources/InfoWatchOS.plist
Building for debugging...
[63/63] Compiling SwiftSoup resource_bundle_accessor.swift
Build complete! (5.22s)
```
This PR fixes the issue by adding the missing excludes (I assume the plists are used by some other build mechanism).

Exclude Info plists from SwiftPM target

---

Package.swift

This PR fixes the warning about missing PrivacyInfo.xcprivary mentioned in package manifest
```
No files found at: /Users/.../.../Tuist/.build/checkouts/SwiftSoup/Sources/PrivacyInfo.xcprivacy
```

Remove copying missing PrivacyInfo

---

Sources/NodeTraversor.swift

NodeTraversor was internal while traverse(_:) was open, making subclassing impossible outside the module. This change makes NodeTraversor open to allow proper subclassing and method overriding.
Resolves #293

fix: make NodeTraversor class open for proper subclassing

---

Sources/Element.swift

After updating from 2.7.7 to 2.8.5, I started getting warnings about unused return variables when calling the `attr` method, such as `try element.attr("font-size", "20px")`. This PR fixes the warnings.

Fix introduced warnings

---

Sources/Element.swift
Tests/SwiftSoupTests/ElementTest.swift

closes #312 
turned out to be a simpler issue than i thought. 
not sure why there's a second `hasClass` with identical logic. is there a tiny performance gain that warrants not doing `hasClass(className.utf8Array)` in the `String` version..?

fix: correct utf8 string length in `hasClass`

---

Sources/Entities.swift
Tests/SwiftSoupTests/BuildEntities.swift

Fix detecting and escaping the No-Break Space Unicode character, which is a two-byte UTF-8 sequence and needs special handling.
Fixes #313.

Fix encoding of U+00A0 No-Break Space

---

SwiftSoup.xcodeproj/project.pbxproj

Removes the explicit deployment targets on the targets, move them to the project instead so all targets use the same deployment targets. Also set them to the values specified in the podspec.
Makes the project compile in Xcode without lots of `'utf8' is only available in application extensions for macOS 10.15 or newer` errors and makes future deployment target changes easier.

Move deployment targets to the project level

---

Sources/Evaluator.swift
Tests/SwiftSoupTests/CssTest.swift

This resolves #274 : the `:first-child` selector included the root node if that node was itself a first child of a non-document node.

Make :first-child ignore the root node

---

Sources/Element.swift
Sources/Evaluator.swift
Tests/SwiftSoupTests/CssTest.swift

Resolves #310 . The evaluator was mixing element and node indices. Simply check whether the element has a next element sibling. Also don't match the root node.

Fix :last-child selector

---

Sources/String.swift

Only uses the `@retroactive` attribute on Swift compilers that support it.

Silence retroactive warnings
